version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/noc/compose"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/soc/compose"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/server/compose"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
